name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.4.0
  emoji_picker_flutter: ^2.2.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/icon2.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  remove_alpha_ios: true
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
